baseurl = "https://stuartwayland.github.io"
title = "Stuart John Wayland"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishdir = "./docs"

[params]
author = "Stuart Wayland"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Stuart Wayland's personal website"
keywords = "blog,developer,personal"
info = ["Masters Student", "University of California, Santa Cruz"]
avatarurl = "images/portrait.jpg"
#gravatar =  
dateFormat = "January 2, 2006"
since = 2022
# Git Commit in Footer, uncomment the line below to enable it
#commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languagues such as Arabic
rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"


# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []
# Custom JS
customJS = []


[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = [
  "'self'",
  "'unsafe-inline'",
  "https://www.google-analytics.com",
  "https://cdn.jsdelivr.net/"
]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/stuartwayland/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 4
url = "https://twitter.com/WaylandStuart"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/stuart-wayland-96b621253/"

[[params.social]]
name = "GoogleScholar"
icon = "fa fa-2x fa-google"
weight = 3
url = "https://scholar.google.com/citations?view_op=list_works&hl=en&user=O27hVK8AAAAJ"

[[params.social]]
name = "Gmail"
icon = "fa fa-2x fa-email-bulk"
weight = 5
url = "mailto:stuartwayland@ucsc.edu"


[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

# [[languages.en.menu.main]]
# name = "Blog"
# weight = 2
# url = "posts/"

[[languages.en.menu.main]]
name = "Research"
weight = 3
url = "research/"

[[languages.en.menu.main]]
name = "CV"
weight = 5
url = "cv/CV_wayland.pdf"

#[[languages.en.menu.main]]
#name = "Transcripts"
#weight = 5
#url = "transcripts/transcripts.pdf"

[[languages.en.menu.main]]
name = "Extracurriculars"
weight = 5
url = "extracurriculars/"

